export const LANGS = [
  { code: 'en', label: 'English' },
  { code: 'it', label: 'Italiano' },
  { code: 'fr', label: 'Français' },
  { code: 'de', label: 'Deutsch' },
  { code: 'es', label: 'Español' },
  { code: 'pt', label: 'Português' },
  { code: 'ro', label: 'Română' },
  { code: 'bg', label: 'Български' },
  { code: 'sq', label: 'Shqip' },
  { code: 'ru', label: 'Русский' },
  { code: 'sv', label: 'Svenska' },
  { code: 'no', label: 'Norsk' },
  { code: 'et', label: 'Eesti' },
  { code: 'lv', label: 'Latviešu' },
  { code: 'lt', label: 'Lietuvių' },
  { code: 'tr', label: 'Türkçe' },
  { code: 'ar', label: 'عربي' },
  { code: 'sw', label: 'Kiswahili' },
  { code: 'hi', label: 'हिन्दी' },
  { code: 'bn', label: 'বাংলা' },
  { code: 'id', label: 'Bahasa Indonesia' },
  { code: 'tl', label: 'Filipino' },
]

export const TAGLINES = {
  en: 'Offline-ready medical triage · Powered by Gemma 4',
  it: 'Triage medico offline · Sviluppato con Gemma 4',
  fr: 'Triage médical hors ligne · Propulsé par Gemma 4',
  de: 'Offline-Medizintriage · Unterstützt von Gemma 4',
  es: 'Triaje médico sin conexión · Impulsado por Gemma 4',
  pt: 'Triagem médica offline · Desenvolvido com Gemma 4',
  ro: 'Triaj medical offline · Dezvoltat cu Gemma 4',
  bg: 'Офлайн медицински триаж · Задвижван от Gemma 4',
  sq: 'Triazh mjekësor offline · Fuqizuar nga Gemma 4',
  ru: 'Офлайн медицинский триаж · На основе Gemma 4',
  sv: 'Offline medicinsk triage · Drivs av Gemma 4',
  no: 'Frakoblet medisinsk triage · Drevet av Gemma 4',
  et: 'Ühenduseta meditsiiniline triaaž · Töötab Gemma 4-ga',
  lv: 'Bezsaistes medicīniskā triāža · Darbina Gemma 4',
  lt: 'Autonominė medicininė triažas · Veikia su Gemma 4',
  tr: 'Çevrimdışı tıbbi triyaj · Gemma 4 ile çalışır',
  ar: 'فرز طبي بدون إنترنت · مدعوم بـ Gemma 4',
  sw: 'Utata wa kimatibabu bila mtandao · Inayotumia Gemma 4',
  hi: 'ऑफलाइन चिकित्सा ट्राइएज · Gemma 4 द्वारा संचालित',
  bn: 'অফলাইন চিকিৎসা ট্রাইয়াজ · Gemma 4 দ্বারা চালিত',
  id: 'Triase medis offline · Didukung oleh Gemma 4',
  tl: 'Offline medikal na triage · Pinapagana ng Gemma 4',
}

const base = {
  agePlaceholder: '34',
  levelRed: 'EMERGENCY',
  levelAmber: 'SEE DOCTOR TODAY',
  levelGreen: 'MONITOR AT HOME',
}

export const LABELS = {
  en: { ...base,
    analyze: 'Analyze symptoms', voice: 'Voice', recording: 'Recording...', loading: 'Analyzing...',
    reset: 'New assessment', histTitle: 'Recent assessments', clearHistory: 'Clear',
    noKey: 'Please enter your Google AI API key.', noSymptoms: 'Please describe the symptoms first.',
    agePlaceholder: 'e.g. 34', symptomsPlaceholder: 'e.g. Fever since 2 days, headache, child aged 4...',
    ageLabel: 'Patient age', sexLabel: 'Sex', pregnantLabel: 'Pregnant',
    sexOptions: ['Select', 'Male', 'Female', 'Other'], pregOptions: ['No', 'Yes', 'Unknown'],
    apiLabel: 'Google AI API Key (Gemma 4)', apiHint: 'Get your free key at aistudio.google.com · Stored locally only',
    disclaimer: 'Not a medical diagnosis. Triage guidance only. Always seek professional care.',
    emergency: 'EMERGENCY — Go to hospital IMMEDIATELY', voiceNotSupported: 'Voice not supported in this browser',
    symptomsLabel: 'Describe symptoms', levelRed: 'EMERGENCY', levelAmber: 'SEE DOCTOR TODAY', levelGreen: 'MONITOR AT HOME',
  },
  it: { ...base,
    analyze: 'Analizza sintomi', voice: 'Voce', recording: 'Registrazione...', loading: 'Analisi in corso...',
    reset: 'Nuova valutazione', histTitle: 'Valutazioni recenti', clearHistory: 'Cancella',
    noKey: 'Inserisci la tua chiave API Google AI.', noSymptoms: 'Descrivi prima i sintomi.',
    agePlaceholder: 'es. 34', symptomsPlaceholder: 'es. Febbre da 2 giorni, mal di testa, bambino di 4 anni...',
    ageLabel: 'Età del paziente', sexLabel: 'Sesso', pregnantLabel: 'Incinta',
    sexOptions: ['Seleziona', 'Maschio', 'Femmina', 'Altro'], pregOptions: ['No', 'Sì', 'Non noto'],
    apiLabel: 'Chiave API Google AI (Gemma 4)', apiHint: 'Ottieni la tua chiave gratuita su aistudio.google.com · Salvata solo in locale',
    disclaimer: 'Non è una diagnosi medica. Solo orientamento al triage. Consulta sempre un professionista.',
    emergency: 'EMERGENZA — Vai in ospedale IMMEDIATAMENTE', voiceNotSupported: 'Voce non supportata in questo browser',
    symptomsLabel: 'Descrivi i sintomi', levelRed: 'EMERGENZA', levelAmber: 'VISITA MEDICA OGGI', levelGreen: 'MONITORA A CASA',
  },
  fr: { ...base,
    analyze: 'Analyser les symptômes', voice: 'Voix', recording: 'Enregistrement...', loading: 'Analyse en cours...',
    reset: 'Nouvelle évaluation', histTitle: 'Évaluations récentes', clearHistory: 'Effacer',
    noKey: 'Veuillez entrer votre clé API Google AI.', noSymptoms: 'Veuillez décrire les symptômes.',
    agePlaceholder: 'ex. 34', symptomsPlaceholder: 'ex. Fièvre depuis 2 jours, maux de tête, enfant de 4 ans...',
    ageLabel: 'Âge du patient', sexLabel: 'Sexe', pregnantLabel: 'Enceinte',
    sexOptions: ['Sélectionner', 'Homme', 'Femme', 'Autre'], pregOptions: ['Non', 'Oui', 'Inconnu'],
    apiLabel: 'Clé API Google AI (Gemma 4)', apiHint: 'Obtenez votre clé gratuite sur aistudio.google.com · Stockée localement',
    disclaimer: 'Pas un diagnostic médical. Conseils de triage uniquement. Consultez toujours un professionnel.',
    emergency: 'URGENCE — Allez à l\'hôpital IMMÉDIATEMENT', voiceNotSupported: 'Voix non supportée dans ce navigateur',
    symptomsLabel: 'Décrire les symptômes', levelRed: 'URGENCE', levelAmber: 'VOIR UN MÉDECIN', levelGreen: 'SURVEILLER À DOMICILE',
  },
  de: { ...base,
    analyze: 'Symptome analysieren', voice: 'Sprache', recording: 'Aufnahme...', loading: 'Analysiere...',
    reset: 'Neue Bewertung', histTitle: 'Letzte Bewertungen', clearHistory: 'Löschen',
    noKey: 'Bitte geben Sie Ihren Google AI API-Schlüssel ein.', noSymptoms: 'Bitte beschreiben Sie zuerst die Symptome.',
    agePlaceholder: 'z.B. 34', symptomsPlaceholder: 'z.B. Fieber seit 2 Tagen, Kopfschmerzen, Kind 4 Jahre...',
    ageLabel: 'Alter des Patienten', sexLabel: 'Geschlecht', pregnantLabel: 'Schwanger',
    sexOptions: ['Auswählen', 'Männlich', 'Weiblich', 'Andere'], pregOptions: ['Nein', 'Ja', 'Unbekannt'],
    apiLabel: 'Google AI API-Schlüssel (Gemma 4)', apiHint: 'Holen Sie sich Ihren kostenlosen Schlüssel auf aistudio.google.com · Nur lokal gespeichert',
    disclaimer: 'Keine medizinische Diagnose. Nur Triage-Orientierung. Wenden Sie sich immer an einen Arzt.',
    emergency: 'NOTFALL — Gehen Sie SOFORT ins Krankenhaus', voiceNotSupported: 'Spracheingabe in diesem Browser nicht unterstützt',
    symptomsLabel: 'Symptome beschreiben', levelRed: 'NOTFALL', levelAmber: 'HEUTE ZUM ARZT', levelGreen: 'ZU HAUSE ÜBERWACHEN',
  },
  es: { ...base,
    analyze: 'Analizar síntomas', voice: 'Voz', recording: 'Grabando...', loading: 'Analizando...',
    reset: 'Nueva evaluación', histTitle: 'Evaluaciones recientes', clearHistory: 'Limpiar',
    noKey: 'Por favor ingrese su clave API de Google AI.', noSymptoms: 'Por favor describa los síntomas primero.',
    agePlaceholder: 'ej. 34', symptomsPlaceholder: 'ej. Fiebre desde 2 días, dolor de cabeza, niño de 4 años...',
    ageLabel: 'Edad del paciente', sexLabel: 'Sexo', pregnantLabel: 'Embarazada',
    sexOptions: ['Seleccionar', 'Masculino', 'Femenino', 'Otro'], pregOptions: ['No', 'Sí', 'Desconocido'],
    apiLabel: 'Clave API Google AI (Gemma 4)', apiHint: 'Obtenga su clave gratuita en aistudio.google.com · Almacenada solo localmente',
    disclaimer: 'No es un diagnóstico médico. Solo orientación de triaje. Siempre busque atención profesional.',
    emergency: 'EMERGENCIA — Vaya al hospital INMEDIATAMENTE', voiceNotSupported: 'Voz no compatible en este navegador',
    symptomsLabel: 'Describir síntomas', levelRed: 'EMERGENCIA', levelAmber: 'VER MÉDICO HOY', levelGreen: 'MONITOREAR EN CASA',
  },
  pt: { ...base,
    analyze: 'Analisar sintomas', voice: 'Voz', recording: 'Gravando...', loading: 'Analisando...',
    reset: 'Nova avaliação', histTitle: 'Avaliações recentes', clearHistory: 'Limpar',
    noKey: 'Por favor insira sua chave API do Google AI.', noSymptoms: 'Por favor descreva os sintomas primeiro.',
    agePlaceholder: 'ex. 34', symptomsPlaceholder: 'ex. Febre há 2 dias, dor de cabeça, criança de 4 anos...',
    ageLabel: 'Idade do paciente', sexLabel: 'Sexo', pregnantLabel: 'Grávida',
    sexOptions: ['Selecionar', 'Masculino', 'Feminino', 'Outro'], pregOptions: ['Não', 'Sim', 'Desconhecido'],
    apiLabel: 'Chave API Google AI (Gemma 4)', apiHint: 'Obtenha sua chave gratuita em aistudio.google.com · Armazenada apenas localmente',
    disclaimer: 'Não é um diagnóstico médico. Apenas orientação de triagem. Sempre procure cuidados profissionais.',
    emergency: 'EMERGÊNCIA — Vá ao hospital IMEDIATAMENTE', voiceNotSupported: 'Voz não suportada neste navegador',
    symptomsLabel: 'Descrever sintomas', levelRed: 'EMERGÊNCIA', levelAmber: 'VER MÉDICO HOJE', levelGreen: 'MONITORAR EM CASA',
  },
  ro: { ...base,
    analyze: 'Analizează simptomele', voice: 'Voce', recording: 'Înregistrare...', loading: 'Analizând...',
    reset: 'Evaluare nouă', histTitle: 'Evaluări recente', clearHistory: 'Șterge',
    noKey: 'Vă rugăm să introduceți cheia API Google AI.', noSymptoms: 'Vă rugăm să descrieți mai întâi simptomele.',
    agePlaceholder: 'ex. 34', symptomsPlaceholder: 'ex. Febră de 2 zile, dureri de cap, copil de 4 ani...',
    ageLabel: 'Vârsta pacientului', sexLabel: 'Sex', pregnantLabel: 'Gravidă',
    sexOptions: ['Selectați', 'Masculin', 'Feminin', 'Altul'], pregOptions: ['Nu', 'Da', 'Necunoscut'],
    apiLabel: 'Cheie API Google AI (Gemma 4)', apiHint: 'Obțineți cheia gratuită pe aistudio.google.com · Stocată doar local',
    disclaimer: 'Nu este un diagnostic medical. Doar orientare de triaj. Consultați întotdeauna un profesionist.',
    emergency: 'URGENȚĂ — Mergeți la spital IMEDIAT', voiceNotSupported: 'Vocea nu este acceptată în acest browser',
    symptomsLabel: 'Descrieți simptomele', levelRed: 'URGENȚĂ', levelAmber: 'MEDIC AZI', levelGreen: 'MONITORIZAȚI ACASĂ',
  },
  bg: { ...base,
    analyze: 'Анализирай симптомите', voice: 'Глас', recording: 'Записване...', loading: 'Анализиране...',
    reset: 'Ново оценяване', histTitle: 'Последни оценки', clearHistory: 'Изчисти',
    noKey: 'Моля въведете вашия Google AI API ключ.', noSymptoms: 'Моля опишете симптомите.',
    agePlaceholder: 'напр. 34', symptomsPlaceholder: 'напр. Треска от 2 дни, главоболие, дете на 4 години...',
    ageLabel: 'Възраст на пациента', sexLabel: 'Пол', pregnantLabel: 'Бременна',
    sexOptions: ['Изберете', 'Мъжки', 'Женски', 'Друго'], pregOptions: ['Не', 'Да', 'Неизвестно'],
    apiLabel: 'Google AI API ключ (Gemma 4)', apiHint: 'Вземете безплатен ключ на aistudio.google.com · Съхранява се само локално',
    disclaimer: 'Не е медицинска диагноза. Само насоки за триаж. Винаги търсете професионална помощ.',
    emergency: 'СПЕШНО — Отидете в болницата НЕЗАБАВНО', voiceNotSupported: 'Гласът не се поддържа в браузъра',
    symptomsLabel: 'Опишете симптомите', levelRed: 'СПЕШНО', levelAmber: 'ЛЕКАР ДНЕС', levelGreen: 'НАБЛЮДАВАЙТЕ У ДОМА',
  },
  sq: { ...base,
    analyze: 'Analizoni simptomat', voice: 'Zë', recording: 'Duke regjistruar...', loading: 'Duke analizuar...',
    reset: 'Vlerësim i ri', histTitle: 'Vlerësimet e fundit', clearHistory: 'Fshi',
    noKey: 'Ju lutemi vendosni çelësin tuaj Google AI API.', noSymptoms: 'Ju lutemi përshkruani simptomat.',
    agePlaceholder: 'p.sh. 34', symptomsPlaceholder: 'p.sh. Ethe prej 2 ditësh, dhimbje koke, fëmijë 4 vjeç...',
    ageLabel: 'Mosha e pacientit', sexLabel: 'Gjinia', pregnantLabel: 'Shtatzënë',
    sexOptions: ['Zgjidhni', 'Mashkull', 'Femër', 'Tjetër'], pregOptions: ['Jo', 'Po', 'E panjohur'],
    apiLabel: 'Çelësi API Google AI (Gemma 4)', apiHint: 'Merrni çelësin tuaj falas në aistudio.google.com · Ruhet vetëm lokalisht',
    disclaimer: 'Nuk është diagnozë mjekësore. Vetëm orientim triazhi. Gjithmonë konsultohuni me profesionist.',
    emergency: 'EMERGJENCË — Shkoni në spital MENJËHERË', voiceNotSupported: 'Zëri nuk mbështetet në këtë shfletues',
    symptomsLabel: 'Përshkruani simptomat', levelRed: 'EMERGJENCË', levelAmber: 'MJEK SOT', levelGreen: 'MONITORONI NË SHTËPI',
  },
  ru: { ...base,
    analyze: 'Анализировать симптомы', voice: 'Голос', recording: 'Запись...', loading: 'Анализ...',
    reset: 'Новая оценка', histTitle: 'Последние оценки', clearHistory: 'Очистить',
    noKey: 'Пожалуйста введите ваш ключ Google AI API.', noSymptoms: 'Пожалуйста опишите симптомы.',
    agePlaceholder: 'напр. 34', symptomsPlaceholder: 'напр. Температура 2 дня, головная боль, ребёнок 4 лет...',
    ageLabel: 'Возраст пациента', sexLabel: 'Пол', pregnantLabel: 'Беременна',
    sexOptions: ['Выбрать', 'Мужской', 'Женский', 'Другой'], pregOptions: ['Нет', 'Да', 'Неизвестно'],
    apiLabel: 'Ключ Google AI API (Gemma 4)', apiHint: 'Получите бесплатный ключ на aistudio.google.com · Хранится только локально',
    disclaimer: 'Не является медицинским диагнозом. Только триажная ориентация. Всегда обращайтесь к специалисту.',
    emergency: 'ЭКСТРЕННО — Немедленно в больницу', voiceNotSupported: 'Голос не поддерживается в этом браузере',
    symptomsLabel: 'Опишите симптомы', levelRed: 'ЭКСТРЕННО', levelAmber: 'К ВРАЧУ СЕГОДНЯ', levelGreen: 'НАБЛЮДАТЬ ДОМА',
  },
  sv: { ...base,
    analyze: 'Analysera symtom', voice: 'Röst', recording: 'Spelar in...', loading: 'Analyserar...',
    reset: 'Ny bedömning', histTitle: 'Senaste bedömningar', clearHistory: 'Rensa',
    noKey: 'Vänligen ange din Google AI API-nyckel.', noSymptoms: 'Vänligen beskriv symptomen först.',
    agePlaceholder: 't.ex. 34', symptomsPlaceholder: 't.ex. Feber sedan 2 dagar, huvudvärk, barn 4 år...',
    ageLabel: 'Patientens ålder', sexLabel: 'Kön', pregnantLabel: 'Gravid',
    sexOptions: ['Välj', 'Man', 'Kvinna', 'Annat'], pregOptions: ['Nej', 'Ja', 'Okänt'],
    apiLabel: 'Google AI API-nyckel (Gemma 4)', apiHint: 'Hämta din gratis nyckel på aistudio.google.com · Lagras bara lokalt',
    disclaimer: 'Inte en medicinsk diagnos. Endast triageorientering. Sök alltid professionell vård.',
    emergency: 'NÖDSITUATION — Gå till sjukhus OMEDELBART', voiceNotSupported: 'Röstinmatning stöds inte i denna webbläsare',
    symptomsLabel: 'Beskriv symtom', levelRed: 'NÖDSITUATION', levelAmber: 'LÄKARE IDAG', levelGreen: 'ÖVERVAKA HEMMA',
  },
  no: { ...base,
    analyze: 'Analyser symptomer', voice: 'Stemme', recording: 'Tar opp...', loading: 'Analyserer...',
    reset: 'Ny vurdering', histTitle: 'Siste vurderinger', clearHistory: 'Fjern',
    noKey: 'Vennligst skriv inn Google AI API-nøkkelen din.', noSymptoms: 'Vennligst beskriv symptomene først.',
    agePlaceholder: 'f.eks. 34', symptomsPlaceholder: 'f.eks. Feber i 2 dager, hodepine, barn 4 år...',
    ageLabel: 'Pasientens alder', sexLabel: 'Kjønn', pregnantLabel: 'Gravid',
    sexOptions: ['Velg', 'Mann', 'Kvinne', 'Annet'], pregOptions: ['Nei', 'Ja', 'Ukjent'],
    apiLabel: 'Google AI API-nøkkel (Gemma 4)', apiHint: 'Få din gratis nøkkel på aistudio.google.com · Lagres kun lokalt',
    disclaimer: 'Ikke en medisinsk diagnose. Kun triageorientering. Søk alltid profesjonell hjelp.',
    emergency: 'NØDSITUASJON — Gå til sykehus UMIDDELBART', voiceNotSupported: 'Stemmeinput støttes ikke i denne nettleseren',
    symptomsLabel: 'Beskriv symptomer', levelRed: 'NØDSITUASJON', levelAmber: 'LEGE I DAG', levelGreen: 'OVERVÅK HJEMME',
  },
  et: { ...base,
    analyze: 'Analüüsi sümptomeid', voice: 'Hääl', recording: 'Salvestamine...', loading: 'Analüüsimine...',
    reset: 'Uus hindamine', histTitle: 'Viimased hindamised', clearHistory: 'Kustuta',
    noKey: 'Palun sisestage oma Google AI API võti.', noSymptoms: 'Palun kirjeldage kõigepealt sümptomeid.',
    agePlaceholder: 'nt. 34', symptomsPlaceholder: 'nt. Palavik 2 päeva, peavalu, laps 4-aastane...',
    ageLabel: 'Patsiendi vanus', sexLabel: 'Sugu', pregnantLabel: 'Rase',
    sexOptions: ['Vali', 'Mees', 'Naine', 'Muu'], pregOptions: ['Ei', 'Jah', 'Teadmata'],
    apiLabel: 'Google AI API võti (Gemma 4)', apiHint: 'Hankige tasuta võti aadressil aistudio.google.com · Salvestatakse ainult lokaalselt',
    disclaimer: 'Ei ole meditsiiniline diagnoos. Ainult triaaži juhendamine. Pöörduge alati spetsialisti poole.',
    emergency: 'HÄDAOLUKORD — Minge KOHE haiglasse', voiceNotSupported: 'Häälsisend ei ole selles brauseris toetatud',
    symptomsLabel: 'Kirjeldage sümptomeid', levelRed: 'HÄDAOLUKORD', levelAmber: 'ARST TÄNA', levelGreen: 'JÄLGI KODUS',
  },
  lv: { ...base,
    analyze: 'Analizēt simptomus', voice: 'Balss', recording: 'Ierakstīšana...', loading: 'Analizē...',
    reset: 'Jauns novērtējums', histTitle: 'Pēdējie novērtējumi', clearHistory: 'Notīrīt',
    noKey: 'Lūdzu ievadiet savu Google AI API atslēgu.', noSymptoms: 'Lūdzu vispirms aprakstiet simptomus.',
    agePlaceholder: 'piem. 34', symptomsPlaceholder: 'piem. Drudzis 2 dienas, galvassāpes, bērns 4 gadi...',
    ageLabel: 'Pacienta vecums', sexLabel: 'Dzimums', pregnantLabel: 'Grūtniece',
    sexOptions: ['Izvēlēties', 'Vīrietis', 'Sieviete', 'Cits'], pregOptions: ['Nē', 'Jā', 'Nezināms'],
    apiLabel: 'Google AI API atslēga (Gemma 4)', apiHint: 'Iegūstiet bezmaksas atslēgu vietnē aistudio.google.com · Tiek glabāta tikai lokāli',
    disclaimer: 'Nav medicīniska diagnoze. Tikai triāžas vadlīnijas. Vienmēr meklējiet profesionālu palīdzību.',
    emergency: 'NEATLIEKAMS — Dodieties uz slimnīcu NEKAVĒJOTIES', voiceNotSupported: 'Balss ievade netiek atbalstīta šajā pārlūkprogrammā',
    symptomsLabel: 'Aprakstiet simptomus', levelRed: 'NEATLIEKAMS', levelAmber: 'ĀRSTS ŠODIEN', levelGreen: 'UZRAUGIET MĀJĀS',
  },
  lt: { ...base,
    analyze: 'Analizuoti simptomus', voice: 'Balsas', recording: 'Įrašoma...', loading: 'Analizuojama...',
    reset: 'Naujas vertinimas', histTitle: 'Paskutiniai vertinimai', clearHistory: 'Išvalyti',
    noKey: 'Įveskite savo Google AI API raktą.', noSymptoms: 'Pirmiausia aprašykite simptomus.',
    agePlaceholder: 'pvz. 34', symptomsPlaceholder: 'pvz. Karščiavimas 2 dienas, galvos skausmas, vaikas 4 metų...',
    ageLabel: 'Paciento amžius', sexLabel: 'Lytis', pregnantLabel: 'Nėščia',
    sexOptions: ['Pasirinkti', 'Vyras', 'Moteris', 'Kita'], pregOptions: ['Ne', 'Taip', 'Nežinoma'],
    apiLabel: 'Google AI API raktas (Gemma 4)', apiHint: 'Gaukite nemokamą raktą aistudio.google.com · Saugoma tik lokaliai',
    disclaimer: 'Tai nėra medicininė diagnozė. Tik triažo orientavimas. Visada kreipkitės į specialistą.',
    emergency: 'SKUBU — Eikite į ligoninę NEDELSIANT', voiceNotSupported: 'Balso įvestis nepalaikoma šioje naršyklėje',
    symptomsLabel: 'Aprašykite simptomus', levelRed: 'SKUBU', levelAmber: 'GYDYTOJAS ŠIANDIEN', levelGreen: 'STEBĖKITE NAMUOSE',
  },
  tr: { ...base,
    analyze: 'Belirtileri analiz et', voice: 'Ses', recording: 'Kaydediliyor...', loading: 'Analiz ediliyor...',
    reset: 'Yeni değerlendirme', histTitle: 'Son değerlendirmeler', clearHistory: 'Temizle',
    noKey: 'Lütfen Google AI API anahtarınızı girin.', noSymptoms: 'Lütfen önce belirtileri açıklayın.',
    agePlaceholder: 'örn. 34', symptomsPlaceholder: 'örn. 2 gündür ateş, baş ağrısı, 4 yaşında çocuk...',
    ageLabel: 'Hasta yaşı', sexLabel: 'Cinsiyet', pregnantLabel: 'Hamile',
    sexOptions: ['Seçin', 'Erkek', 'Kadın', 'Diğer'], pregOptions: ['Hayır', 'Evet', 'Bilinmiyor'],
    apiLabel: 'Google AI API Anahtarı (Gemma 4)', apiHint: 'Ücretsiz anahtarınızı aistudio.google.com adresinden alın · Yalnızca yerel olarak depolanır',
    disclaimer: 'Tıbbi tanı değildir. Sadece triyaj yönlendirmesi. Her zaman bir uzmana başvurun.',
    emergency: 'ACİL — HEMEN hastaneye gidin', voiceNotSupported: 'Bu tarayıcıda ses girişi desteklenmiyor',
    symptomsLabel: 'Belirtileri açıklayın', levelRed: 'ACİL', levelAmber: 'BUGÜN DOKTORA', levelGreen: 'EVDE TAKİP EDİN',
  },
  ar: { ...base,
    analyze: 'تحليل الأعراض', voice: 'صوت', recording: 'جاري التسجيل...', loading: 'جاري التحليل...',
    reset: 'تقييم جديد', histTitle: 'التقييمات الأخيرة', clearHistory: 'مسح',
    noKey: 'يرجى إدخال مفتاح Google AI API.', noSymptoms: 'يرجى وصف الأعراض أولاً.',
    agePlaceholder: 'مثال 34', symptomsPlaceholder: 'مثال حمى منذ يومين، صداع، طفل عمره 4 سنوات...',
    ageLabel: 'عمر المريض', sexLabel: 'الجنس', pregnantLabel: 'حامل',
    sexOptions: ['اختر', 'ذكر', 'أنثى', 'آخر'], pregOptions: ['لا', 'نعم', 'غير معروف'],
    apiLabel: 'مفتاح Google AI API (Gemma 4)', apiHint: 'احصل على مفتاحك المجاني على aistudio.google.com · مخزن محلياً فقط',
    disclaimer: 'هذا ليس تشخيصاً طبياً. إرشادات الفرز فقط. استشر دائماً متخصصاً.',
    emergency: 'طارئ — اذهب إلى المستشفى فوراً', voiceNotSupported: 'الإدخال الصوتي غير مدعوم في هذا المتصفح',
    symptomsLabel: 'وصف الأعراض', levelRed: 'طارئ', levelAmber: 'زيارة طبيب اليوم', levelGreen: 'مراقبة في المنزل',
  },
  sw: { ...base,
    analyze: 'Changanua dalili', voice: 'Sauti', recording: 'Inarekodiwa...', loading: 'Inachambua...',
    reset: 'Tathmini mpya', histTitle: 'Tathmini za hivi karibuni', clearHistory: 'Futa',
    noKey: 'Tafadhali ingiza ufunguo wako wa API ya Google AI.', noSymptoms: 'Tafadhali eleza dalili kwanza.',
    agePlaceholder: 'mfano 34', symptomsPlaceholder: 'mfano Homa siku 2, maumivu ya kichwa, mtoto wa miaka 4...',
    ageLabel: 'Umri wa mgonjwa', sexLabel: 'Jinsia', pregnantLabel: 'Mimba',
    sexOptions: ['Chagua', 'Mwanaume', 'Mwanamke', 'Nyingine'], pregOptions: ['Hapana', 'Ndiyo', 'Haijulikani'],
    apiLabel: 'Ufunguo wa API ya Google AI (Gemma 4)', apiHint: 'Pata ufunguo wako bure kwenye aistudio.google.com · Huhifadhiwa ndani tu',
    disclaimer: 'Si utambuzi wa kimatibabu. Mwongozo wa utata tu. Daima tafuta huduma ya kitaalamu.',
    emergency: 'DHARURA — Nenda hospitalini MARA MOJA', voiceNotSupported: 'Sauti haiwezekani katika kivinjari hiki',
    symptomsLabel: 'Eleza dalili', levelRed: 'DHARURA', levelAmber: 'ONA DAKTARI LEO', levelGreen: 'FUATILIA NYUMBANI',
  },
  hi: { ...base,
    analyze: 'लक्षण विश्लेषण करें', voice: 'आवाज़', recording: 'रिकॉर्डिंग...', loading: 'विश्लेषण हो रहा है...',
    reset: 'नया मूल्यांकन', histTitle: 'हाल के मूल्यांकन', clearHistory: 'साफ करें',
    noKey: 'कृपया अपनी Google AI API कुंजी दर्ज करें।', noSymptoms: 'कृपया पहले लक्षण बताएं।',
    agePlaceholder: 'जैसे 34', symptomsPlaceholder: 'जैसे 2 दिन से बुखार, सिरदर्द, 4 साल का बच्चा...',
    ageLabel: 'मरीज़ की आयु', sexLabel: 'लिंग', pregnantLabel: 'गर्भवती',
    sexOptions: ['चुनें', 'पुरुष', 'महिला', 'अन्य'], pregOptions: ['नहीं', 'हाँ', 'अज्ञात'],
    apiLabel: 'Google AI API कुंजी (Gemma 4)', apiHint: 'aistudio.google.com पर मुफ़्त कुंजी पाएं · केवल स्थानीय रूप से संग्रहीत',
    disclaimer: 'यह चिकित्सा निदान नहीं है। केवल ट्राइएज मार्गदर्शन। हमेशा पेशेवर देखभाल लें।',
    emergency: 'आपातकाल — तुरंत अस्पताल जाएं', voiceNotSupported: 'इस ब्राउज़र में वॉयस इनपुट समर्थित नहीं है',
    symptomsLabel: 'लक्षण बताएं', levelRed: 'आपातकाल', levelAmber: 'आज डॉक्टर से मिलें', levelGreen: 'घर पर देखभाल',
  },
  bn: { ...base,
    analyze: 'উপসর্গ বিশ্লেষণ করুন', voice: 'ভয়েস', recording: 'রেকর্ড হচ্ছে...', loading: 'বিশ্লেষণ হচ্ছে...',
    reset: 'নতুন মূল্যায়ন', histTitle: 'সাম্প্রতিক মূল্যায়ন', clearHistory: 'মুছুন',
    noKey: 'অনুগ্রহ করে আপনার Google AI API কী লিখুন।', noSymptoms: 'অনুগ্রহ করে প্রথমে উপসর্গ বর্ণনা করুন।',
    agePlaceholder: 'যেমন ৩৪', symptomsPlaceholder: 'যেমন ২ দিন ধরে জ্বর, মাথাব্যথা, ৪ বছরের শিশু...',
    ageLabel: 'রোগীর বয়স', sexLabel: 'লিঙ্গ', pregnantLabel: 'গর্ভবতী',
    sexOptions: ['নির্বাচন করুন', 'পুরুষ', 'মহিলা', 'অন্যান্য'], pregOptions: ['না', 'হ্যাঁ', 'অজানা'],
    apiLabel: 'Google AI API কী (Gemma 4)', apiHint: 'aistudio.google.com এ বিনামূল্যে কী পান · শুধুমাত্র স্থানীয়ভাবে সংরক্ষিত',
    disclaimer: 'এটি চিকিৎসা নির্ণয় নয়। শুধুমাত্র ট্রাইয়াজ নির্দেশনা। সর্বদা পেশাদার সেবা নিন।',
    emergency: 'জরুরি — এখনই হাসপাতালে যান', voiceNotSupported: 'এই ব্রাউজারে ভয়েস ইনপুট সমর্থিত নয়',
    symptomsLabel: 'উপসর্গ বর্ণনা করুন', levelRed: 'জরুরি', levelAmber: 'আজ ডাক্তার দেখান', levelGreen: 'বাড়িতে পর্যবেক্ষণ করুন',
  },
  id: { ...base,
    analyze: 'Analisis gejala', voice: 'Suara', recording: 'Merekam...', loading: 'Menganalisis...',
    reset: 'Penilaian baru', histTitle: 'Penilaian terbaru', clearHistory: 'Hapus',
    noKey: 'Silakan masukkan kunci API Google AI Anda.', noSymptoms: 'Silakan deskripsikan gejalanya terlebih dahulu.',
    agePlaceholder: 'mis. 34', symptomsPlaceholder: 'mis. Demam 2 hari, sakit kepala, anak 4 tahun...',
    ageLabel: 'Usia pasien', sexLabel: 'Jenis kelamin', pregnantLabel: 'Hamil',
    sexOptions: ['Pilih', 'Laki-laki', 'Perempuan', 'Lainnya'], pregOptions: ['Tidak', 'Ya', 'Tidak diketahui'],
    apiLabel: 'Kunci API Google AI (Gemma 4)', apiHint: 'Dapatkan kunci gratis Anda di aistudio.google.com · Disimpan hanya secara lokal',
    disclaimer: 'Bukan diagnosis medis. Hanya panduan triase. Selalu cari perawatan profesional.',
    emergency: 'DARURAT — Segera pergi ke rumah sakit', voiceNotSupported: 'Input suara tidak didukung di browser ini',
    symptomsLabel: 'Deskripsikan gejala', levelRed: 'DARURAT', levelAmber: 'DOKTER HARI INI', levelGreen: 'PANTAU DI RUMAH',
  },
  tl: { ...base,
    analyze: 'Suriin ang mga sintomas', voice: 'Boses', recording: 'Nagre-record...', loading: 'Sinusuri...',
    reset: 'Bagong pagtatasa', histTitle: 'Mga kamakailang pagtatasa', clearHistory: 'Burahin',
    noKey: 'Pakiusap ilagay ang iyong Google AI API key.', noSymptoms: 'Pakiusap ilarawan muna ang mga sintomas.',
    agePlaceholder: 'hal. 34', symptomsPlaceholder: 'hal. Lagnat 2 araw, sakit ng ulo, bata 4 taong gulang...',
    ageLabel: 'Edad ng pasyente', sexLabel: 'Kasarian', pregnantLabel: 'Buntis',
    sexOptions: ['Pumili', 'Lalaki', 'Babae', 'Iba pa'], pregOptions: ['Hindi', 'Oo', 'Hindi alam'],
    apiLabel: 'Google AI API Key (Gemma 4)', apiHint: 'Kumuha ng libreng key sa aistudio.google.com · Naka-imbak nang lokal lamang',
    disclaimer: 'Hindi ito medikal na diagnosis. Gabay sa triage lamang. Laging humingi ng propesyonal na pag-aalaga.',
    emergency: 'EMERHENSYA — Pumunta sa ospital AGAD', voiceNotSupported: 'Hindi sinusuportahan ang voice input sa browser na ito',
    symptomsLabel: 'Ilarawan ang mga sintomas', levelRed: 'EMERHENSYA', levelAmber: 'DOKTOR NGAYON', levelGreen: 'SUBAYBAYAN SA BAHAY',
  },
}
