export const LANGS = [
  { code: 'en', label: 'English' },
  { code: 'fr', label: 'Français' },
  { code: 'sw', label: 'Kiswahili' },
  { code: 'hi', label: 'हिन्दी' },
  { code: 'pt', label: 'Português' },
  { code: 'ar', label: 'عربي' },
  { code: 'es', label: 'Español' },
  { code: 'it', label: 'Italiano' },
]

export const TAGLINES = {
  en: 'Offline-ready medical triage · Powered by Gemma 4',
  fr: 'Triage médical hors ligne · Propulsé par Gemma 4',
  sw: 'Utata wa kimatibabu bila mtandao · Inayotumia Gemma 4',
  hi: 'ऑफलाइन चिकित्सा ट्राइएज · Gemma 4 द्वारा संचालित',
  pt: 'Triagem médica offline · Desenvolvido com Gemma 4',
  ar: 'فرز طبي بدون إنترنت · مدعوم بـ Gemma 4',
  es: 'Triaje médico sin conexión · Impulsado por Gemma 4',
  it: 'Triage medico offline · Sviluppato con Gemma 4',
}

export const LABELS = {
  en: {
    analyze: 'Analyze symptoms',
    voice: 'Voice',
    recording: 'Recording...',
    loading: 'Analyzing...',
    reset: 'New assessment',
    histTitle: 'Recent assessments',
    clearHistory: 'Clear',
    noKey: 'Please enter your Google AI API key to use TriageFirst.',
    noSymptoms: 'Please describe the symptoms first.',
    agePlaceholder: 'e.g. 34',
    symptomsPlaceholder: 'e.g. Fever since 2 days, headache, no appetite, child aged 4...',
    ageLabel: 'Patient age',
    sexLabel: 'Sex',
    pregnantLabel: 'Pregnant',
    sexOptions: ['Select', 'Male', 'Female', 'Other'],
    pregOptions: ['No', 'Yes', 'Unknown'],
    apiLabel: 'Google AI API Key (Gemma 4)',
    apiHint: 'Get your free key at aistudio.google.com · Stored locally only',
    disclaimer: 'Not a medical diagnosis. This tool provides triage guidance only — like a trained nurse at a hospital entrance. Always seek professional care when in doubt.',
    emergency: 'EMERGENCY — Go to hospital IMMEDIATELY',
    voiceNotSupported: 'Voice input not supported in this browser',
    symptomsLabel: 'Describe symptoms',
    levelRed: 'EMERGENCY',
    levelAmber: 'SEE DOCTOR TODAY',
    levelGreen: 'MONITOR AT HOME',
  },
  fr: {
    analyze: 'Analyser les symptômes',
    voice: 'Voix',
    recording: 'Enregistrement...',
    loading: 'Analyse en cours...',
    reset: 'Nouvelle évaluation',
    histTitle: 'Évaluations récentes',
    clearHistory: 'Effacer',
    noKey: 'Veuillez entrer votre clé API Google AI.',
    noSymptoms: 'Veuillez décrire les symptômes.',
    agePlaceholder: 'ex. 34',
    symptomsPlaceholder: 'ex. Fièvre depuis 2 jours, maux de tête, enfant de 4 ans...',
    ageLabel: 'Âge du patient',
    sexLabel: 'Sexe',
    pregnantLabel: 'Enceinte',
    sexOptions: ['Sélectionner', 'Homme', 'Femme', 'Autre'],
    pregOptions: ['Non', 'Oui', 'Inconnu'],
    apiLabel: 'Clé API Google AI (Gemma 4)',
    apiHint: 'Obtenez votre clé gratuite sur aistudio.google.com · Stockée localement uniquement',
    disclaimer: 'Pas un diagnostic médical. Cet outil fournit uniquement des conseils de triage. Consultez toujours un professionnel de santé.',
    emergency: 'URGENCE — Allez à l\'hôpital IMMÉDIATEMENT',
    voiceNotSupported: 'Saisie vocale non supportée dans ce navigateur',
    symptomsLabel: 'Décrire les symptômes',
    levelRed: 'URGENCE',
    levelAmber: 'VOIR UN MÉDECIN',
    levelGreen: 'SURVEILLER À DOMICILE',
  },
  sw: {
    analyze: 'Changanua dalili',
    voice: 'Sauti',
    recording: 'Inarekodiwa...',
    loading: 'Inachambua...',
    reset: 'Tathmini mpya',
    histTitle: 'Tathmini za hivi karibuni',
    clearHistory: 'Futa',
    noKey: 'Tafadhali ingiza ufunguo wako wa API ya Google AI.',
    noSymptoms: 'Tafadhali eleza dalili kwanza.',
    agePlaceholder: 'mfano 34',
    symptomsPlaceholder: 'mfano Homa siku 2, maumivu ya kichwa, mtoto wa miaka 4...',
    ageLabel: 'Umri wa mgonjwa',
    sexLabel: 'Jinsia',
    pregnantLabel: 'Mimba',
    sexOptions: ['Chagua', 'Mwanaume', 'Mwanamke', 'Nyingine'],
    pregOptions: ['Hapana', 'Ndiyo', 'Haijulikani'],
    apiLabel: 'Ufunguo wa API ya Google AI (Gemma 4)',
    apiHint: 'Pata ufunguo wako bure kwenye aistudio.google.com · Huhifadhiwa ndani tu',
    disclaimer: 'Si utambuzi wa kimatibabu. Zana hii hutoa mwongozo wa utata tu. Daima tafuta huduma ya kitaalamu.',
    emergency: 'DHARURA — Nenda hospitalini MARA MOJA',
    voiceNotSupported: 'Sauti haiwezekani katika kivinjari hiki',
    symptomsLabel: 'Eleza dalili',
    levelRed: 'DHARURA',
    levelAmber: 'ONA DAKTARI LEO',
    levelGreen: 'FUATILIA NYUMBANI',
  },
  hi: {
    analyze: 'लक्षण विश्लेषण करें',
    voice: 'आवाज़',
    recording: 'रिकॉर्डिंग...',
    loading: 'विश्लेषण हो रहा है...',
    reset: 'नया मूल्यांकन',
    histTitle: 'हाल के मूल्यांकन',
    clearHistory: 'साफ करें',
    noKey: 'कृपया अपनी Google AI API कुंजी दर्ज करें।',
    noSymptoms: 'कृपया पहले लक्षण बताएं।',
    agePlaceholder: 'जैसे 34',
    symptomsPlaceholder: 'जैसे 2 दिन से बुखार, सिरदर्द, 4 साल का बच्चा...',
    ageLabel: 'मरीज़ की आयु',
    sexLabel: 'लिंग',
    pregnantLabel: 'गर्भवती',
    sexOptions: ['चुनें', 'पुरुष', 'महिला', 'अन्य'],
    pregOptions: ['नहीं', 'हाँ', 'अज्ञात'],
    apiLabel: 'Google AI API कुंजी (Gemma 4)',
    apiHint: 'aistudio.google.com पर मुफ़्त कुंजी पाएं · केवल स्थानीय रूप से संग्रहीत',
    disclaimer: 'यह चिकित्सा निदान नहीं है। यह उपकरण केवल ट्राइएज मार्गदर्शन प्रदान करता है। हमेशा पेशेवर देखभाल लें।',
    emergency: 'आपातकाल — तुरंत अस्पताल जाएं',
    voiceNotSupported: 'इस ब्राउज़र में वॉयस इनपुट समर्थित नहीं है',
    symptomsLabel: 'लक्षण बताएं',
    levelRed: 'आपातकाल',
    levelAmber: 'आज डॉक्टर से मिलें',
    levelGreen: 'घर पर देखभाल',
  },
  pt: {
    analyze: 'Analisar sintomas',
    voice: 'Voz',
    recording: 'Gravando...',
    loading: 'Analisando...',
    reset: 'Nova avaliação',
    histTitle: 'Avaliações recentes',
    clearHistory: 'Limpar',
    noKey: 'Por favor insira sua chave API do Google AI.',
    noSymptoms: 'Por favor descreva os sintomas primeiro.',
    agePlaceholder: 'ex. 34',
    symptomsPlaceholder: 'ex. Febre há 2 dias, dor de cabeça, criança de 4 anos...',
    ageLabel: 'Idade do paciente',
    sexLabel: 'Sexo',
    pregnantLabel: 'Grávida',
    sexOptions: ['Selecionar', 'Masculino', 'Feminino', 'Outro'],
    pregOptions: ['Não', 'Sim', 'Desconhecido'],
    apiLabel: 'Chave API Google AI (Gemma 4)',
    apiHint: 'Obtenha sua chave gratuita em aistudio.google.com · Armazenada apenas localmente',
    disclaimer: 'Não é um diagnóstico médico. Esta ferramenta fornece apenas orientação de triagem. Sempre procure cuidados profissionais.',
    emergency: 'EMERGÊNCIA — Vá ao hospital IMEDIATAMENTE',
    voiceNotSupported: 'Entrada de voz não suportada neste navegador',
    symptomsLabel: 'Descrever sintomas',
    levelRed: 'EMERGÊNCIA',
    levelAmber: 'VER MÉDICO HOJE',
    levelGreen: 'MONITORAR EM CASA',
  },
  ar: {
    analyze: 'تحليل الأعراض',
    voice: 'صوت',
    recording: 'جاري التسجيل...',
    loading: 'جاري التحليل...',
    reset: 'تقييم جديد',
    histTitle: 'التقييمات الأخيرة',
    clearHistory: 'مسح',
    noKey: 'يرجى إدخال مفتاح Google AI API.',
    noSymptoms: 'يرجى وصف الأعراض أولاً.',
    agePlaceholder: 'مثال 34',
    symptomsPlaceholder: 'مثال حمى منذ يومين، صداع، طفل عمره 4 سنوات...',
    ageLabel: 'عمر المريض',
    sexLabel: 'الجنس',
    pregnantLabel: 'حامل',
    sexOptions: ['اختر', 'ذكر', 'أنثى', 'آخر'],
    pregOptions: ['لا', 'نعم', 'غير معروف'],
    apiLabel: 'مفتاح Google AI API (Gemma 4)',
    apiHint: 'احصل على مفتاحك المجاني على aistudio.google.com · مخزن محلياً فقط',
    disclaimer: 'هذا ليس تشخيصاً طبياً. تقدم هذه الأداة إرشادات الفرز فقط. استشر دائماً متخصصاً.',
    emergency: 'طارئ — اذهب إلى المستشفى فوراً',
    voiceNotSupported: 'الإدخال الصوتي غير مدعوم في هذا المتصفح',
    symptomsLabel: 'وصف الأعراض',
    levelRed: 'طارئ',
    levelAmber: 'زيارة طبيب اليوم',
    levelGreen: 'مراقبة في المنزل',
  },
  es: {
    analyze: 'Analizar síntomas',
    voice: 'Voz',
    recording: 'Grabando...',
    loading: 'Analizando...',
    reset: 'Nueva evaluación',
    histTitle: 'Evaluaciones recientes',
    clearHistory: 'Limpiar',
    noKey: 'Por favor ingrese su clave API de Google AI.',
    noSymptoms: 'Por favor describa los síntomas primero.',
    agePlaceholder: 'ej. 34',
    symptomsPlaceholder: 'ej. Fiebre desde 2 días, dolor de cabeza, niño de 4 años...',
    ageLabel: 'Edad del paciente',
    sexLabel: 'Sexo',
    pregnantLabel: 'Embarazada',
    sexOptions: ['Seleccionar', 'Masculino', 'Femenino', 'Otro'],
    pregOptions: ['No', 'Sí', 'Desconocido'],
    apiLabel: 'Clave API Google AI (Gemma 4)',
    apiHint: 'Obtenga su clave gratuita en aistudio.google.com · Almacenada solo localmente',
    disclaimer: 'No es un diagnóstico médico. Esta herramienta proporciona solo orientación de triaje. Siempre busque atención profesional.',
    emergency: 'EMERGENCIA — Vaya al hospital INMEDIATAMENTE',
    voiceNotSupported: 'Entrada de voz no compatible en este navegador',
    symptomsLabel: 'Describir síntomas',
    levelRed: 'EMERGENCIA',
    levelAmber: 'VER MÉDICO HOY',
    levelGreen: 'MONITOREAR EN CASA',
  },
  it: {
    analyze: 'Analizza sintomi',
    voice: 'Voce',
    recording: 'Registrazione...',
    loading: 'Analisi in corso...',
    reset: 'Nuova valutazione',
    histTitle: 'Valutazioni recenti',
    clearHistory: 'Cancella',
    noKey: 'Inserisci la tua chiave API Google AI.',
    noSymptoms: 'Descrivi prima i sintomi.',
    agePlaceholder: 'es. 34',
    symptomsPlaceholder: 'es. Febbre da 2 giorni, mal di testa, bambino di 4 anni...',
    ageLabel: 'Età del paziente',
    sexLabel: 'Sesso',
    pregnantLabel: 'Incinta',
    sexOptions: ['Seleziona', 'Maschio', 'Femmina', 'Altro'],
    pregOptions: ['No', 'Sì', 'Non noto'],
    apiLabel: 'Chiave API Google AI (Gemma 4)',
    apiHint: 'Ottieni la tua chiave gratuita su aistudio.google.com · Salvata solo in locale',
    disclaimer: 'Non è una diagnosi medica. Questo strumento fornisce solo orientamento al triage. Consulta sempre un professionista sanitario.',
    emergency: 'EMERGENZA — Vai in ospedale IMMEDIATAMENTE',
    voiceNotSupported: 'Input vocale non supportato in questo browser',
    symptomsLabel: 'Descrivi i sintomi',
    levelRed: 'EMERGENZA',
    levelAmber: 'VISITA MEDICA OGGI',
    levelGreen: 'MONITORA A CASA',
  },
}
